# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ShoppingTracker.Web/* 

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: PowerShell@2
  displayName: 'Angular Build'
  inputs:
    targetType: 'inline'
    script: |
      cd ./ShoppingTracker.Web
      npm install
      npm run build -- --prod --base-href ./ --outputPath=$(Pipeline.Workspace)/dist/ --configuration='production'
 
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\dist\'
    artifact: 'ShoppingTracker.Web/'
    publishLocation: 'pipeline'
