/**
 * PsStoreFavorites.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GamePrice {
    id?: string;
    platform?: string;
    classification?: string;
    name?: string;
    price?: string;
    discountedPrice?: string;
    discount?: string;
    media?: string;
}