/**
 * ShoppingTracker.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ShoppingFavorite {
    name?: string;
    price?: string;
    discountedPrice?: string;
    discount?: string;
    discountDate?: Date;
    favoritesDate?: Date;
    media?: string;
    partitionKey?: string;
    rowKey?: string;
    timestamp?: Date;
    eTag?: string;
    store: Stores;
}

export enum Stores {
    PSStore,
    GameStop,
    Amazon,
    ALL = 999
}
